'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WebServicePersona
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Persona", [Namespace]:="http://schemas.datacontract.org/2004/07/ModelABMLPersona"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Persona
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EdadField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaNacimientoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreCompletoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SexoField As Char
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Edad() As Integer
            Get
                Return Me.EdadField
            End Get
            Set
                If (Me.EdadField.Equals(value) <> true) Then
                    Me.EdadField = value
                    Me.RaisePropertyChanged("Edad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaNacimiento() As Date
            Get
                Return Me.FechaNacimientoField
            End Get
            Set
                If (Me.FechaNacimientoField.Equals(value) <> true) Then
                    Me.FechaNacimientoField = value
                    Me.RaisePropertyChanged("FechaNacimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreCompleto() As String
            Get
                Return Me.NombreCompletoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreCompletoField, value) <> true) Then
                    Me.NombreCompletoField = value
                    Me.RaisePropertyChanged("NombreCompleto")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sexo() As Char
            Get
                Return Me.SexoField
            End Get
            Set
                If (Me.SexoField.Equals(value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WebServicePersona.IServiceABMLPersona")>  _
    Public Interface IServiceABMLPersona
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceABMLPersona/ListadoPersonas", ReplyAction:="http://tempuri.org/IServiceABMLPersona/ListadoPersonasResponse")>  _
        Function ListadoPersonas() As WebServicePersona.Persona()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceABMLPersona/Existe", ReplyAction:="http://tempuri.org/IServiceABMLPersona/ExisteResponse")>  _
        Function Existe(ByVal nombreCompleto As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceABMLPersona/Grabar", ReplyAction:="http://tempuri.org/IServiceABMLPersona/GrabarResponse")>  _
        Function Grabar(ByVal nombreCompleto As String, ByVal fechaNacimiento As String, ByVal edad As Integer, ByVal sexo As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceABMLPersona/Borrar", ReplyAction:="http://tempuri.org/IServiceABMLPersona/BorrarResponse")>  _
        Function Borrar(ByVal nombreCompleto As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceABMLPersona/BuscarPersona", ReplyAction:="http://tempuri.org/IServiceABMLPersona/BuscarPersonaResponse")>  _
        Function BuscarPersona(ByVal nombreCompleto As String) As WebServicePersona.Persona
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceABMLPersona/Actualizar", ReplyAction:="http://tempuri.org/IServiceABMLPersona/ActualizarResponse")>  _
        Function Actualizar(ByVal nombreAModificar As String, ByVal nuevoNombre As String, ByVal fechaNacimiento As String, ByVal edad As Integer, ByVal sexo As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceABMLPersonaChannel
        Inherits WebServicePersona.IServiceABMLPersona, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceABMLPersonaClient
        Inherits System.ServiceModel.ClientBase(Of WebServicePersona.IServiceABMLPersona)
        Implements WebServicePersona.IServiceABMLPersona
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListadoPersonas() As WebServicePersona.Persona() Implements WebServicePersona.IServiceABMLPersona.ListadoPersonas
            Return MyBase.Channel.ListadoPersonas
        End Function
        
        Public Function Existe(ByVal nombreCompleto As String) As Boolean Implements WebServicePersona.IServiceABMLPersona.Existe
            Return MyBase.Channel.Existe(nombreCompleto)
        End Function
        
        Public Function Grabar(ByVal nombreCompleto As String, ByVal fechaNacimiento As String, ByVal edad As Integer, ByVal sexo As String) As Boolean Implements WebServicePersona.IServiceABMLPersona.Grabar
            Return MyBase.Channel.Grabar(nombreCompleto, fechaNacimiento, edad, sexo)
        End Function
        
        Public Function Borrar(ByVal nombreCompleto As String) As Boolean Implements WebServicePersona.IServiceABMLPersona.Borrar
            Return MyBase.Channel.Borrar(nombreCompleto)
        End Function
        
        Public Function BuscarPersona(ByVal nombreCompleto As String) As WebServicePersona.Persona Implements WebServicePersona.IServiceABMLPersona.BuscarPersona
            Return MyBase.Channel.BuscarPersona(nombreCompleto)
        End Function
        
        Public Function Actualizar(ByVal nombreAModificar As String, ByVal nuevoNombre As String, ByVal fechaNacimiento As String, ByVal edad As Integer, ByVal sexo As String) As Boolean Implements WebServicePersona.IServiceABMLPersona.Actualizar
            Return MyBase.Channel.Actualizar(nombreAModificar, nuevoNombre, fechaNacimiento, edad, sexo)
        End Function
    End Class
End Namespace
