USE [master]
GO

/****** Object:  Database [Persona]    Script Date: 26/9/2018 9:26:51 a. m. ******/
CREATE DATABASE [Persona]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Persona', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Persona.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Persona_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Persona_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Persona] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Persona].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Persona] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Persona] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Persona] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Persona] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Persona] SET ARITHABORT OFF 
GO

ALTER DATABASE [Persona] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Persona] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Persona] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Persona] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Persona] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Persona] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Persona] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Persona] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Persona] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Persona] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Persona] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Persona] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Persona] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Persona] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Persona] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Persona] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Persona] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Persona] SET RECOVERY FULL 
GO

ALTER DATABASE [Persona] SET  MULTI_USER 
GO

ALTER DATABASE [Persona] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Persona] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Persona] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Persona] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Persona] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Persona] SET QUERY_STORE = OFF
GO

USE [Persona]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Persona] SET  READ_WRITE 
GO


